# Generated by Django 4.1.3 on 2023-03-14 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0004_admin"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64, verbose_name="项目名")),
                (
                    "level",
                    models.SmallIntegerField(
                        choices=[(1, "非常紧急"), (2, "紧急"), (3, "重要"), (4, "一般")],
                        default=4,
                        verbose_name="级别",
                    ),
                ),
                ("detail", models.TextField(verbose_name="详细描述")),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app01.userinfo",
                        verbose_name="负责人",
                    ),
                ),
            ],
        ),
    ]
